/******************************************************************************
 * Filename:       GSensor_Service.c
 *
 * Description:    This file contains the implementation of the service.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3139.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.8
 *                 Time:        Thu Aug 10 2017 00:17:18 GMT+08:00
 *

 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **********************************************************************************/


/*********************************************************************
 * INCLUDES
 */
#include <string.h>

//#define xdc_runtime_Log_DISABLE_ALL 1  // Add to disable logs from this file
#include <xdc/runtime/Log.h>
#include <xdc/runtime/Diags.h>

#include "bcomdef.h"
#include "OSAL.h"
#include "linkdb.h"
#include "att.h"
#include "gatt.h"
#include "gatt_uuid.h"
#include "gattservapp.h"
#include "gapbondmgr.h"

#ifdef ICALL_LITE
#  include "icall_api.h" // Only exists for 3.x stack version, so use ifdef.
#endif

#include "gsensor_service.h"
#include <ti/drivers/PIN.h>
#include "project_zero.h"
#include <Board.h>
/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * CONSTANTS
 */

/*********************************************************************
 * TYPEDEFS
 */

/*********************************************************************
* GLOBAL VARIABLES
*/

// GSensor_Service Service UUID
CONST uint8_t GsensorServiceUUID[ATT_UUID_SIZE] =
{
  GSENSOR_SERVICE_SERV_UUID_BASE128(GSENSOR_SERVICE_SERV_UUID)
};

// position UUID
CONST uint8_t gs_PositionUUID[ATT_UUID_SIZE] =
{
  GS_POSITION_UUID_BASE128(GS_POSITION_UUID)
};

// oriention_axis UUID
CONST uint8_t gs_Oriention_axisUUID[ATT_UUID_SIZE] =
{
  GS_ORIENTION_AXIS_UUID_BASE128(GS_ORIENTION_AXIS_UUID)
};

// wake_up_state UUID
CONST uint8_t gs_Wake_up_stateUUID[ATT_UUID_SIZE] =
{
  GS_WAKE_UP_STATE_UUID_BASE128(GS_WAKE_UP_STATE_UUID)
};


/*********************************************************************
 * LOCAL VARIABLES
 */

static GsensorServiceCBs_t *pAppCBs = NULL;
static uint8_t gs_icall_rsp_task_id = INVALID_TASK_ID;

/*********************************************************************
* Profile Attributes - variables
*/

// Service declaration
static CONST gattAttrType_t GsensorServiceDecl = { ATT_UUID_SIZE, GsensorServiceUUID };

// Characteristic "position" Properties (for declaration)
static uint8_t gs_PositionProps = GATT_PROP_NOTIFY | GATT_PROP_READ;

// Characteristic "position" Value variable
static uint8_t gs_PositionVal[GS_POSITION_LEN] = {0};

// Length of data in characteristic "position" Value variable, initialized to minimal size.
static uint16_t gs_PositionValLen = GS_POSITION_LEN_MIN;

// Characteristic "position" Client Characteristic Configuration Descriptor
static gattCharCfg_t *gs_PositionConfig;



// Characteristic "oriention axis" Properties (for declaration)
static uint8_t gs_Oriention_axisProps = GATT_PROP_NOTIFY | GATT_PROP_READ;

// Characteristic "oriention axis" Value variable
static uint8_t gs_Oriention_axisVal[GS_ORIENTION_AXIS_LEN] = {0};

// Length of data in characteristic "oriention axis" Value variable, initialized to minimal size.
static uint16_t gs_Oriention_axisValLen = GS_ORIENTION_AXIS_LEN_MIN;

// Characteristic "oriention axis" Client Characteristic Configuration Descriptor
static gattCharCfg_t *gs_Oriention_axisConfig;



// Characteristic "wake up state" Properties (for declaration)
static uint8_t gs_Wake_up_stateProps = GATT_PROP_NOTIFY | GATT_PROP_READ;

// Characteristic "wake up state" Value variable
static uint8_t gs_Wake_up_stateVal[GS_WAKE_UP_STATE_LEN] = {0};

// Length of data in characteristic "wake up state" Value variable, initialized to minimal size.
static uint16_t gs_Wake_up_stateValLen = GS_WAKE_UP_STATE_LEN_MIN;

// Characteristic "wake up state" Client Characteristic Configuration Descriptor
static gattCharCfg_t *gs_Wake_up_stateConfig;



/*********************************************************************
* Profile Attributes - Table
*/

static gattAttribute_t GSensor_ServiceAttrTbl[] =
{
  // GSensor_Service Service Declaration
  {
    { ATT_BT_UUID_SIZE, primaryServiceUUID },
    GATT_PERMIT_READ,
    0,
    (uint8_t *)&GsensorServiceDecl
  },
    // position Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &gs_PositionProps
    },
      // position Characteristic Value
      {
        { ATT_UUID_SIZE, gs_PositionUUID },
        GATT_PERMIT_READ,
        0,
        gs_PositionVal
      },
      // position CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&gs_PositionConfig
      },
    // oriention axis Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &gs_Oriention_axisProps
    },
      // oriention axis Characteristic Value
      {
        { ATT_UUID_SIZE, gs_Oriention_axisUUID },
        GATT_PERMIT_READ,
        0,
        gs_Oriention_axisVal
      },
      // oriention axis CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&gs_Oriention_axisConfig
      },
    // wake up state Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &gs_Wake_up_stateProps
    },
      // wake up state Characteristic Value
      {
        { ATT_UUID_SIZE, gs_Wake_up_stateUUID },
        GATT_PERMIT_READ,
        0,
        gs_Wake_up_stateVal
      },
      // wake up state CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&gs_Wake_up_stateConfig
      },
};

/*********************************************************************
 * LOCAL FUNCTIONS
 */
static bStatus_t GSensor_Service_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                           uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                           uint16_t maxLen, uint8_t method );
static bStatus_t GSensor_Service_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                            uint8_t *pValue, uint16_t len, uint16_t offset,
                                            uint8_t method );

/*********************************************************************
 * PROFILE CALLBACKS
 */
// Simple Profile Service Callbacks
CONST gattServiceCBs_t GSensor_ServiceCBs =
{
  GSensor_Service_ReadAttrCB,  // Read callback function pointer
  GSensor_Service_WriteAttrCB, // Write callback function pointer
  NULL                       // Authorization callback function pointer
};

/*********************************************************************
* PUBLIC FUNCTIONS
*/

/*
 * GsensorService_AddService- Initializes the GsensorService service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t GsensorService_AddService( uint8_t rspTaskId )
{
  uint8_t status;

  // Allocate Client Characteristic Configuration table
  gs_PositionConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( gs_PositionConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, gs_PositionConfig );
  // Allocate Client Characteristic Configuration table
  gs_Oriention_axisConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( gs_Oriention_axisConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, gs_Oriention_axisConfig );
  // Allocate Client Characteristic Configuration table
  gs_Wake_up_stateConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( gs_Wake_up_stateConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, gs_Wake_up_stateConfig );
  // Register GATT attribute list and CBs with GATT Server App
  status = GATTServApp_RegisterService( GSensor_ServiceAttrTbl,
                                        GATT_NUM_ATTRS( GSensor_ServiceAttrTbl ),
                                        GATT_MAX_ENCRYPT_KEY_SIZE,
                                        &GSensor_ServiceCBs );
  Log_info1("Registered service, %d attributes", (IArg)GATT_NUM_ATTRS( GSensor_ServiceAttrTbl ));
  gs_icall_rsp_task_id = rspTaskId;

  return ( status );
}

/*
 * GsensorService_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
bStatus_t GsensorService_RegisterAppCBs( GsensorServiceCBs_t *appCallbacks )
{
  if ( appCallbacks )
  {
    pAppCBs = appCallbacks;
    Log_info1("Registered callbacks to application. Struct %p", (IArg)appCallbacks);
    return ( SUCCESS );
  }
  else
  {
    Log_warning0("Null pointer given for app callbacks.");
    return ( FAILURE );
  }
}

/*
 * GsensorService_SetParameter - Set a GsensorService parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t GsensorService_SetParameter( uint8_t param, uint16_t len, void *value )
{
  bStatus_t ret = SUCCESS;
  uint8_t  *pAttrVal;
  uint16_t *pValLen;
  uint16_t valMinLen;
  uint16_t valMaxLen;
  uint8_t sendNotiInd = FALSE;
  gattCharCfg_t *attrConfig;
  uint8_t needAuth;
  PIN_setOutputValue(triggerPinHandle, extern_trigger, 1);//for oscilloscope
  switch ( param )
  {
    case GS_POSITION_ID:
      pAttrVal  =  gs_PositionVal;
      pValLen   = &gs_PositionValLen;
      valMinLen =  GS_POSITION_LEN_MIN;
      valMaxLen =  GS_POSITION_LEN;
      sendNotiInd = TRUE;
      attrConfig  = gs_PositionConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"Position", (IArg)len);
      break;

    case GS_ORIENTION_AXIS_ID:
      pAttrVal  =  gs_Oriention_axisVal;
      pValLen   = &gs_Oriention_axisValLen;
      valMinLen =  GS_ORIENTION_AXIS_LEN_MIN;
      valMaxLen =  GS_ORIENTION_AXIS_LEN;
      sendNotiInd = TRUE;
      attrConfig  = gs_Oriention_axisConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"Oriention_axis", (IArg)len);
      break;

    case GS_WAKE_UP_STATE_ID:
      pAttrVal  =  gs_Wake_up_stateVal;
      pValLen   = &gs_Wake_up_stateValLen;
      valMinLen =  GS_WAKE_UP_STATE_LEN_MIN;
      valMaxLen =  GS_WAKE_UP_STATE_LEN;
      sendNotiInd = TRUE;
      attrConfig  = gs_Wake_up_stateConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"Wake_up_state", (IArg)len);
      break;

    default:
      Log_error1("SetParameter: Parameter #%d not valid.", (IArg)param);
      return INVALIDPARAMETER;
  }

  // Check bounds, update value and send notification or indication if possible.
  if ( len <= valMaxLen && len >= valMinLen )
  {
    memcpy(pAttrVal, value, len);
    *pValLen = len; // Update length for read and get.

    if (sendNotiInd)
    {
      Log_info2("Transmitting noti/ind- connHandle %d, %s", (IArg)attrConfig[0].connHandle,
                                                    (IArg)( (attrConfig[0].value==0)?"Noti/ind disabled":
                                                    (attrConfig[0].value==1)?"Notification enabled":
                                                     "Indication enabled" ) );
      // Try to send notification.
      GATTServApp_ProcessCharCfg( attrConfig, pAttrVal, needAuth,
                                  GSensor_ServiceAttrTbl, GATT_NUM_ATTRS( GSensor_ServiceAttrTbl ),
                                  gs_icall_rsp_task_id,  GSensor_Service_ReadAttrCB);
    }
  }
  else
  {
    Log_error3("Length outside bounds: Len: %d MinLen: %d MaxLen: %d.", (IArg)len, (IArg)valMinLen, (IArg)valMaxLen);
    ret = bleInvalidRange;
  }

  return ret;
}


/*
 * GsensorService_GetParameter - Get a GsensorService parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t GsensorService_GetParameter( uint8_t param, uint16_t *len, void *value )
{
  bStatus_t ret = SUCCESS;
  switch ( param )
  {
    default:
      Log_error1("GetParameter: Parameter #%d not valid.", (IArg)param);
      ret = INVALIDPARAMETER;
      break;
  }
  return ret;
}

/*********************************************************************
 * @internal
 * @fn          GSensor_Service_findCharParamId
 *
 * @brief       Find the logical param id of an attribute in the service's attr table.
 *
 *              Works only for Characteristic Value attributes and
 *              Client Characteristic Configuration Descriptor attributes.
 *
 * @param       pAttr - pointer to attribute
 *
 * @return      uint8_t paramID (ref GSensor_Service.h) or 0xFF if not found.
 */
static uint8_t GSensor_Service_findCharParamId(gattAttribute_t *pAttr)
{
  // Is this a Client Characteristic Configuration Descriptor?
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
    return GSensor_Service_findCharParamId(pAttr - 1); // Assume the value attribute precedes CCCD and recurse

  // Is this attribute in "position"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, gs_PositionUUID, pAttr->type.len))
    return GS_POSITION_ID;

  // Is this attribute in "oriention axis"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, gs_Oriention_axisUUID, pAttr->type.len))
    return GS_ORIENTION_AXIS_ID;

  // Is this attribute in "wake up state"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, gs_Wake_up_stateUUID, pAttr->type.len))
    return GS_WAKE_UP_STATE_ID;

  else
    return 0xFF; // Not found. Return invalid.
}

/*********************************************************************
 * @fn          GSensor_Service_ReadAttrCB
 *
 * @brief       Read an attribute.
 *
 * @param       connHandle - connection message was received on
 * @param       pAttr - pointer to attribute
 * @param       pValue - pointer to data to be read
 * @param       pLen - length of data to be read
 * @param       offset - offset of the first octet to be read
 * @param       maxLen - maximum length of data to be read
 * @param       method - type of read message
 *
 * @return      SUCCESS, blePending or Failure
 */
static bStatus_t GSensor_Service_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                       uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                       uint16_t maxLen, uint8_t method )
{
  bStatus_t status = SUCCESS;
  uint16_t valueLen;
  uint8_t paramID = 0xFF;

  // Find settings for the characteristic to be read.
  paramID = GSensor_Service_findCharParamId( pAttr );
  switch ( paramID )
  {
    case GS_POSITION_ID:
      valueLen = gs_PositionValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"Position",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for position can be inserted here */
      break;

    case GS_ORIENTION_AXIS_ID:
      valueLen = gs_Oriention_axisValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"Oriention_axis",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for oriention axis can be inserted here */
      break;

    case GS_WAKE_UP_STATE_ID:
      valueLen = gs_Wake_up_stateValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"Wake_up_state",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for wake up state can be inserted here */
      break;

    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
  // Check bounds and return the value
  if ( offset > valueLen )  // Prevent malicious ATT ReadBlob offsets.
  {
    Log_error0("An invalid offset was requested.");
    status = ATT_ERR_INVALID_OFFSET;
  }
  else
  {
    *pLen = MIN(maxLen, valueLen - offset);  // Transmit as much as possible
    memcpy(pValue, pAttr->pValue + offset, *pLen);
  }

  return status;
}

/*********************************************************************
 * @fn      GSensor_Service_WriteAttrCB
 *
 * @brief   Validate attribute data prior to a write operation
 *
 * @param   connHandle - connection message was received on
 * @param   pAttr - pointer to attribute
 * @param   pValue - pointer to data to be written
 * @param   len - length of data
 * @param   offset - offset of the first octet to be written
 * @param   method - type of write message
 *
 * @return  SUCCESS, blePending or Failure
 */
static bStatus_t GSensor_Service_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                        uint8_t *pValue, uint16_t len, uint16_t offset,
                                        uint8_t method )
{
  bStatus_t status  = SUCCESS;
  uint8_t   paramID = 0xFF;

  // See if request is regarding a Client Characterisic Configuration
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
  {
    // Allow notification and indication, but do not check if really allowed per CCCD.
    status = GATTServApp_ProcessCCCWriteReq( connHandle, pAttr, pValue, len,
                                             offset, GATT_CLIENT_CFG_NOTIFY |
                                                     GATT_CLIENT_CFG_INDICATE );
    if (SUCCESS == status && pAppCBs && pAppCBs->pfnCfgChangeCb)
       pAppCBs->pfnCfgChangeCb( connHandle, GSENSOR_SERVICE_SERV_UUID,
                                GSensor_Service_findCharParamId(pAttr), pValue, len );

     return status;
  }

  // Find settings for the characteristic to be written.
  paramID = GSensor_Service_findCharParamId( pAttr );
  switch ( paramID )
  {
    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
}
