/******************************************************************************
 * Filename:       GSensor_Service.h
 *
 * Description:    This file contains the GSensor_Service service definitions and
 *                 prototypes.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3139.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.8
 *                 Time:        Thu Aug 10 2017 00:17:18 GMT+08:00
 *

 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef _GSENSOR_SERVICE_H_
#define _GSENSOR_SERVICE_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include <bcomdef.h>

/*********************************************************************
 * CONSTANTS
 */
// Service UUID
#define GSENSOR_SERVICE_SERV_UUID 0x42EE
#define GSENSOR_SERVICE_SERV_UUID_BASE128(uuid) 0x7D, 0xE9, 0xCD, 0xA5, 0x89, 0x04, 0xB1, 0xB0, 0x54, 0x45, 0xC7, 0x01, LO_UINT16(uuid), HI_UINT16(uuid), 0x73, 0x92

// position Characteristic defines
#define GS_POSITION_ID                 0
#define GS_POSITION_UUID               0x52E0
#define GS_POSITION_UUID_BASE128(uuid) 0x7D, 0xE9, 0xCD, 0xA5, 0x89, 0x04, 0xB1, 0xB0, 0x54, 0x45, 0xC7, 0x01, LO_UINT16(uuid), HI_UINT16(uuid), 0x73, 0x92
#define GS_POSITION_LEN                20
#define GS_POSITION_LEN_MIN            1

// oriention axis Characteristic defines
#define GS_ORIENTION_AXIS_ID                 1
#define GS_ORIENTION_AXIS_UUID               0x12B7
#define GS_ORIENTION_AXIS_UUID_BASE128(uuid) 0x7D, 0xE9, 0xCD, 0xA5, 0x89, 0x04, 0xB1, 0xB0, 0x54, 0x45, 0xC7, 0x01, LO_UINT16(uuid), HI_UINT16(uuid), 0x73, 0x92
#define GS_ORIENTION_AXIS_LEN                10
#define GS_ORIENTION_AXIS_LEN_MIN            1

// wake up state Characteristic defines
#define GS_WAKE_UP_STATE_ID                 2
#define GS_WAKE_UP_STATE_UUID               0xC574
#define GS_WAKE_UP_STATE_UUID_BASE128(uuid) 0x7D, 0xE9, 0xCD, 0xA5, 0x89, 0x04, 0xB1, 0xB0, 0x54, 0x45, 0xC7, 0x01, LO_UINT16(uuid), HI_UINT16(uuid), 0x73, 0x92
#define GS_WAKE_UP_STATE_LEN                20
#define GS_WAKE_UP_STATE_LEN_MIN            1

/*********************************************************************
 * TYPEDEFS
 */

// Fields in characteristic "position"
//   Field "position" format: uint8[], bits: -1

// Fields in characteristic "oriention axis"

// Fields in characteristic "wake up state"

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * Profile Callbacks
 */

// Callback when a characteristic value has changed
typedef void (*GsensorServiceChange_t)( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );

typedef struct
{
  GsensorServiceChange_t        pfnChangeCb;     // Called when characteristic value changes
  GsensorServiceChange_t        pfnCfgChangeCb;  // Called when characteristic CCCD changes
} GsensorServiceCBs_t;



/*********************************************************************
 * API FUNCTIONS
 */


/*
 * GsensorService_AddService- Initializes the GsensorService service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t GsensorService_AddService( uint8_t rspTaskId );

/*
 * GsensorService_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
extern bStatus_t GsensorService_RegisterAppCBs( GsensorServiceCBs_t *appCallbacks );

/*
 * GsensorService_SetParameter - Set a GsensorService parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t GsensorService_SetParameter( uint8_t param, uint16_t len, void *value );

/*
 * GsensorService_GetParameter - Get a GsensorService parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t GsensorService_GetParameter( uint8_t param, uint16_t *len, void *value );

/*********************************************************************
*********************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* _GSENSOR_SERVICE_H_ */

